blogs/urls.py
from django.urls import path, include
from . import views


appname = 'blogs'


urlpatterns = [
    path('', views.blog, name="blogs"),
    path('<slug:slug>/', views.blogpost, name="post"),
    
]

courses/urls.py
from django.urls import path, include
from . import views


app_name = 'courses'


urlpatterns = [
    path('<slug:course_name>/<int:id>/', views.course, name="course"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('blogs/', include('blogs.urls')),
    path('courses/', include('courses.urls')),
]

blogs/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Blog(models.Model):
    name = models.CharField(max_length=200)
    body = RichTextField(config_name='default')
    slug = models.SlugField()
    date = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.name

courses/models.py
from django.db import models


# Create your models here.
class Course(models.Model):
    course_name = models.CharField(max_length=200)
    topic = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField()
    
    def __str__(self):
        return f"{self.course_name} ({self.topic})"
    
    

blogs/views.py
from django.shortcuts import render, HttpResponse
from .models import Blog

# Create your views here.
def blog(request):
    blogs = Blog.objects.all().order_by('-date')
    return render(request, 'blogs.html', {'blogs':blogs})


def blogpost(request, slug):
    blog = Blog.objects.get(slug=slug)
    return render(request, 'post.html', {'blog':blog})

courses/views.py
from django.shortcuts import render
from .models import Course

# Create your views here.

def course(request, course_name, id):
    course = Course.objects.get(course_name=course_name, id=id)
    course_topics = Course.objects.filter(course_name=course_name)
    
    current_index = list(course_topics).index(course)
    
    prev_topic = None
    next_topic = None
    
    if current_index > 0:
        prev_topic = course_topics[current_index - 1]
        
    if current_index < len(course_topics) - 1:
        next_topic = course_topics[current_index + 1]
    
    
    context = {
        'course': course,
        'course_topics': course_topics,
        'prev_topic': prev_topic,
        'next_topic': next_topic,
    }
    return render(request, 'course_page.html', context=context)

mysite/views.py
from django.shortcuts import render, HttpResponse

def home(request):
    return render(request, "index.html")

blogs/templates/blogs.html
{% extends "layout.html" %}
{% block title %}Blogs{% endblock %}
{% load static %}
{% block content %}
  <!-- bloglist -->
  <div class="container mt-5">
    {% for blog in blogs %}
    <div class="box">
      <h3 class="title"><a href="{% url 'post' slug=blog.slug %}" class="link">{{blog.name}}</a></h3>
      <p>Posted on {{blog.date}}</p>
    </div>
    <hr>
    {% endfor %}
  </div>
{% endblock %}

blogs/templates/post.html
{% extends "layout.html" %} 
{% block title %}{% endblock %}
{% block content %}

<div class="container mt-2 w-75">
  <h2 class="mt-3 text-center">{{blog.name}}</h2>
  <p class="text-center">
        {{blog.body | safe }}
  </p>
</div>


{% endblock %}

courses/templates/course_page.html
{% extends "layout.html" %} {%load static%} {% block content %}
<!-- Toggle Sidebar Button -->
<button class="btn toggle-sidebar">
  <i class="bi bi-list"></i>
</button>

<!-- Wrapper -->
<div class="wrapper">
  <!-- Sidebar -->
  <div class="sidebar" id="sidebar">
    <div class="p-4">
      <h5 class="mt-4 coursename">{{course.course_name}}</h5>
      <ul class="list-unstyled">
        {% for topic in course_topics %}
        <li class="py-1 px-1">
          <a href="{% url 'courses:course' topic.course_name topic.id %}">{{topic.topic}}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>

  <!-- Content Area -->
  <div class="content my-2 d-flex flex-column align-items-center" id="content">
    <h1 class="my-3">{{course.topic}}</h1>
    <div class="my-3 topic-content">{{course.body | safe }}</div>

    <!-- Button Row -->
    <div class="row mt-5 w-75">
      <div class="col text-start">
        {% if prev_topic %}
        <button class="btn prev-next-btn">
          <a href="{% url 'courses:course' prev_topic.course_name prev_topic.id %}">Prev</a>
        </button>
        {% else %}
        <button class="btn prev-next-btn" disabled>Prev</button>
        {% endif %}
      </div>
      <div class="col text-end">
        {% if next_topic %}
        <button class="btn prev-next-btn">
          <a href="{% url 'courses:course' next_topic.course_name next_topic.id %}">Next</a>
        </button>
        {% else %}
        <button class="btn prev-next-btn" disabled>Next</button>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<!-- Custom JS -->
<script>
  document
    .querySelector(".toggle-sidebar")
    .addEventListener("click", function () {
      document.getElementById("sidebar").classList.toggle("collapsed");
      document.getElementById("content").classList.toggle("collapsed");
    });
  document.addEventListener("DOMContentLoaded", (event) => {
    hljs.highlightAll();
  });
</script>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% load static %}
{% block content %}
  <!-- hero section -->
  <div class="container-fluid hero-section p-5">
    <div class="row">
      <!-- Left Text Column -->
      <div class="col-md-6 hero-text">
        <h1 class="display-4">Unlock Your Coding Potential with CodeQuantum</h1>
        <p class="lead">Master coding with tailored courses, expert blogs, and community support.</p>
        <a href="#" class="btn btn-lg m-2 get-started">Get Started</a>
      </div>
      <!-- Right Image Column -->
      <div class="col-md-6 hero-img text-center">
        <img src="{% static 'images/hero.jpg' %}" alt="Hero Image">
      </div>
    </div>
  </div>

  <!-- Features Section -->
  <div class="container py-5">
    <div class="row text-center">
      <div class="col-md-4">
        <i class="bi bi-laptop fs-1 text-primary"></i>
        <h3 class="my-3">Tailored Courses</h3>
        <p>Learn coding with courses designed to fit your skill level and interests.</p>
      </div>
      <div class="col-md-4">
        <i class="bi bi-people fs-1 text-primary"></i>
        <h3 class="my-3">Community Support</h3>
        <p>Get support from our active coding community and peer mentors.</p>
      </div>
      <div class="col-md-4">
        <i class="bi bi-book fs-1 text-primary"></i>
        <h3 class="my-3">Expert Blogs</h3>
        <p>Stay updated with the latest trends and tips from industry experts.</p>
      </div>
    </div>
  </div>


<!-- Courses Section -->
<div class="container py-5">
  <div class="text-center mb-5">
    <h2>Our Popular Courses</h2>
    <p>Choose from a wide range of expertly designed courses.</p>
  </div>
  <div class="row d-flex justify-content-center">
    <div class="col-md-4 course">
      <div class="card h-100">
        <img src="{% static 'images/datastructure.jpg' %}" class="card-img-top" alt="Course 1">
        <div class="card-body">
          <h5 class="card-title">DSA</h5>
          <p class="card-text">Learn Data Structures and algorithms for coding interviews.</p>
          <a href="#" class="btn btn-primary">Enroll Now</a>
        </div>
      </div>
    </div>
    <div class="col-md-4 course">
      <div class="card h-100">
        <img src="{% static 'images/datascience.jpg' %}" class="card-img-top" alt="Course 2">
        <div class="card-body">
          <h5 class="card-title">Data Science</h5>
          <p class="card-text">Master data analysis, machine learning, and Python programming.</p>
          <a href="#" class="btn btn-primary">Enroll Now</a>
        </div>
      </div>
    </div>
    <div class="col-md-4 course">
      <div class="card h-100">
        <img src="{% static 'images/djangoimg.avif' %}" class="card-img-top" alt="Course 3">
        <div class="card-body">
          <h5 class="card-title">Django</h5>
          <p class="card-text">Master Django to make powerful backend for webpages.</p>
          <a href="#" class="btn btn-primary">Enroll Now</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!--highlight js-->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/atom-one-dark.min.css"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/python.min.js"></script>
    <script>
      document.addEventListener("DOMContentLoaded", (event) => {
        hljs.highlightAll();
      });
    </script>

    {% block head %}{% endblock %}
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">CodeQuantum</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0 mr-5 me-5">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Courses</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blogs' %}">Blogs</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/">Login/Register</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}

    <!-- Footer -->
    <footer class="bg-black text-white py-4">
      <div class="container text-center">
        <p>&copy; 2024 CodeQuantum. All Rights Reserved.</p>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#" class="text-white">Privacy Policy</a>
          </li>
          <li class="list-inline-item">
            <a href="#" class="text-white">Terms of Service</a>
          </li>
        </ul>
        <div>
          <a href="#" class="text-white mx-2"><i class="bi bi-facebook"></i></a>
          <a href="#" class="text-white mx-2"><i class="bi bi-twitter"></i></a>
          <a href="#" class="text-white mx-2"
            ><i class="bi bi-instagram"></i
          ></a>
        </div>
      </div>
    </footer>

    <!--script-->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>